### PR TITLE
Pcc08 House Inventory Tracker

### PR DESCRIPTION
**Pull request by mridubhatnagar**
ATTENTION: before clicking "Create Pull Request" please submit some meta data, thanks!

**Difficulty level (1-10)**: 7
**Estimated time spent (hours)**: more than expected 
**Completed (yes/no)**: Yes
**I stretched my coding skills (if yes what did you learn?):** 
1. Tried doing it using object oriented programming concepts.
2. Deciding the data structure to store data. Figuring out would dictionary inside list work fine.
Or nested dictionary would work fine.
3. After a long time tried making menu based program.
4. Use of **kwargs and list compreshension.

**Features in the current implementation**
1. Prints room name, item name and corresponding cost for each item.
2. Computes total cost of all the items in the mentioned rooms.
3. Menu based.
4. Iterable. List details of room of your choice.
5. Get count of total rooms in the house.

**Pending**
Update feature. 

**Other feedback (what can we improve?)**: 
Step by step instructions are nice.
I await more blog challenges. Keep them coming. :)

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
Closed this pull request to check issue with uneccessary files

**Comment by mridubhatnagar** [comment]
Keeping the same PR

**Comment by pybites** [comment]
Same here: please delete 03/newplot.png

**Comment by mridubhatnagar** [comment]
> Same here: please delete 03/newplot.png

I am unable to delete it

**Pull request closed without merging**
