### PR TITLE
Solved CH01 and working on CH02

### PR DESCRIPTION
**Pull request by kokasha**
ATTENTION: before clicking "Create Pull Request" please submit some meta data, thanks!

Difficulty level (1-10): []
Estimated time spent (hours): []
Completed (yes/no): []
I stretched my coding skills (if yes what did you learn?): []
Other feedback (what can we improve?): []

### CODE REVIEW

**Comment by kokasha** [comment]
Solved CH01 and CH02

**Comment by kokasha** [comment]
Solved CH01 and working on CH02

**Comment by jcastle13** [comment]
Hello @kokasha.  I would try, next time, to separate the PR.  It's not a 'must have' but a cleaner way to go about when reviewing each PCC separately.  Thanks.

**Comment by bbelderbos** [comment]
thanks @jcastle13, tried to remove files of PCC02, but also seeing a rename of the PCC01 template file which doesn't seem good. @kokasha please follow the PR instructions on https://codechalleng.es/challenges/

**Pull request closed without merging**
