### PR TITLE
PCC17 jhervas

### PR DESCRIPTION
**Pull request by JoseHervas**
Hi! This is my first submission to the Challenges. I'm also new to github so I hope everything is ok, but let me know if I did something wrong during the submission (my email is on my github profile). I'm excited to be part of the PyBites community!

Greetings from Spain!

### CODE REVIEW

**Comment by pybites** [comment]
Awesome, merging it into community base branch, thanks. De donde? Saludos desde Alicante

**Comment by JoseHervas** [comment]
Gracias :+1: Qué sorpresa! Yo de Barcelona. Un saludo desde el norte!

**Comment by pybites** [comment]
Hola Jose, te gusta el Reddit API? Esta semana podrias aprovechar nuestro nuevo reto para hacer algo chulo :)

**Comment by mridubhatnagar** [comment]
@JoseHervas hey, I am trying to run my script so that it runs daily and I receive an email notification. By using schedule module how did you manage to do it.  Did you run your script python filename.py and kept it running?

**Pull request merged**
