### PR TITLE
PCC14 - Write DRY Code With Decorators

### PR DESCRIPTION
**Pull request by zkan**
Difficulty level (1-10): [1]
Estimated time spent (hours): [1]
Completed (yes/no): [Yes]
I stretched my coding skills (if yes what did you learn?): []
Other feedback (what can we improve?): []

### CODE REVIEW

**Comment by pybites** [comment]
@zkan, nice use of a decorator, can I steal this idea to add an Bite exercise on our platform?

**Comment by zkan** [comment]
@pybites Sure! Please do.

**Comment by bbelderbos** [comment]
OK my variation - what do you think?

```def strip_range(start, end):
    """Decorator that replaces characters of a text by dots, from 'start'
       (inclusive) to 'end' (exclusive) = like `range`.

        So applying this decorator on a function like this and 'text'
        being 'hello world' it would convert it into 'Hel.. world' when
        applied like this:
        
        @strip_range(3, 5)
        def gen_output(text):
            return text
    """
    pass ```

e.g.

```
    @strip_range(3, 5)
    def gen_output(text='Hello world'):
        return text
```

Would output: `'Hel.. world'`

**Comment by zkan** [comment]
@bbelderbos Wow! I love your idea. 👍

**Comment by bbelderbos** [comment]
@zkan nice to hear. It's up: https://codechalleng.es/bites/152/ - as it's a Premium Bite I unlocked it for you so you can code it on our platform. Thanks for the idea!

**Pull request merged**
