### PR TITLE
first submission, be gentle!

### PR DESCRIPTION
**Pull request by dseptem**
random quote + quote's author biography from wikipedia (if possible)
uses flask + pywebview for a 'simple view' with no css and flask + your browser for a 'web view' with CSS

hope im doing all this github stuff right!

### CODE REVIEW

**Comment by pybites** [comment]
Awesome, I will take a look, thanks. 

Please merge into community. It was easy for me to change though (thanks GH - https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/)

**Comment by pybites** [comment]
Very nice result. There are some refactorings you could do, send us an email if interested: pybitesblog at gmail dot com

**Comment by pybites** [comment]
I also added a requirements.txt file for the dependencies

**Comment by dseptem** [comment]
sent that email!

**Pull request merged**
