### PR TITLE
PCC52 codebymark

### PR DESCRIPTION
**Pull request by codebymark**
Difficulty level (1-10): [5]
Estimated time spent (hours): [3]
Completed (yes/no): [Yes]
I stretched my coding skills (if yes what did you learn?): [My first challenge and push! I learned a lot.
- How the datetime, date and timedelta modules work.
- Don't just start coding - use pen and paper first to write down what you want to achieve.
- I'd like to tidy up the output, find a way to make the remaining time dynamic so it doesn't just keeping printing down the whole window.
- Also parts of the code is repetitive.]

Other feedback (what can we improve?): [n/a]

### CODE REVIEW

**Comment by bbelderbos** [comment]
Glad to hear, nice feedback, thanks

**Comment by codebymark** [comment]
Thanks @bbelderbos, Julian and Michael for putting together a great course. The integration with the PyBytes platform really helps to reinforce what I'm learning.

**Comment by pybites** [comment]
Wow @codebymark supernice to hear, thanks. How is it going? Looking forward to more PRs ...

**Comment by codebymark** [comment]
Thanks for merging 👍I'm learning lots 🎓 🤓

**Pull request merged**
