### PR TITLE
My first real pull request. 

### PR DESCRIPTION
**Pull request by fmitchell259**
ATTENTION: before clicking "Create Pull Request" please submit some meta data, thanks!

Difficulty level (1-10): 3

Estimated time spent (hours): 2

Completed (yes/no): yes

I stretched my coding skills (if yes what did you learn?): yes, I learned how to read a file, strip it of unneccassery elements and make it into a list. I also learned how tuples worked and used this knowledge to correctly locate letters and scores within the scrabble_scores list. 

Other feedback (what can we improve?): Absolutely nothing for you to improve. I LOVED tackling this challenge, I just really need feedback on my code as well my use of gitHub in general. I have read the guidelines and beginner tutorials, so anything I have missed please point it out.

### CODE REVIEW

**Comment by fmitchell259** [comment]
Hi guys, 

Again, I'm not sure I have correctly understood the pull-request flow when it comes to these public repositories . I deleted all the unnecessary files from my branch but would that effect a merge if you accepted my solution to the problem? 

Apologies if I haven't followed the correct process and please correct me where I'm going wrong. 

Some insight into my solution would be fantastic as well. 

many thanks
Frank

**Comment by fmitchell259** [comment]
@jcastle13 thank for changing the base branch fro master to community. Can you just explain the reasoning though. 

Is it because what I am proposing is a little solution to the problem that, of which I'm looking for feedback? And the master branch is for the most 'optimum' solution? 

Thanks again for taking the time to complete this task for me in the first place. :)

**Comment by jcastle13** [comment]
It's nothing to do with your solution.  For all PR we merge them into the community branch.  If you look through the 'Git Setup' instructions it mentions the checkout to the community branch.  Whenever you are done with your code then you will want to commit all changes into that branch.  One way to figure out which branch you are working on is to type 'git branch' then you will see which current branch you are currently on.  The master branch is for the template challenge information whereas community branch is for the community to share their code.  Hopefully that helps :)

**Comment by fmitchell259** [comment]
> It's nothing to do with your solution. For all PR we merge them into the community branch. If you look through the 'Git Setup' instructions it mentions the checkout to the community branch. Whenever you are done with your code then you will want to commit all changes into that branch. One way to figure out which branch you are working on is to type 'git branch' then you will see which current branch you are currently on. The master branch is for the template challenge information whereas community branch is for the community to share their code. Hopefully that helps :)

that clears things up a lot,thank you so much for your help jcastle :) 

I plan on completing more challenges so knowing which branch to commit changes to :) 

Thanks Again.
Frank

**Comment by jcastle13** [comment]
Just FYI.  Make sure next time you modify the directory you are working on and not the readme file in the community section.  If you like you can add a read me file in the directory you are working on instead.  :)

**Pull request merged**
