### PR TITLE
Pcc03

### PR DESCRIPTION
**Pull request by wcontractor**
Difficulty level (1-10): [5]
Estimated time spent (hours): [4]
Completed (yes/no): [Maybe?]
I stretched my coding skills (if yes what did you learn?): [Learned more about different libraries - itertools, difflib, and collections ]
Other feedback (what can we improve?): [I could not get the code to pass the test script.  The get_similarities function would not pass.  Even the posted solution would not work, something must have changed.]

### CODE REVIEW

**Comment by bbelderbos** [comment]
Thanks for your feedback, which tests did you use? My test_tags.py on the solutions branch runs fine:

```$ nosetests
...
----------------------------------------------------------------------
Ran 3 tests in 0.099s

OK```


```[bobbelderbos@imac 03 (solutions)]$ wc -l tags.py test_tags.py
      49 tags.py
      48 test_tags.py
      97 total``

**Comment by bbelderbos** [comment]
let me push the solutions branch to make sure all is up2date

**Comment by bbelderbos** [comment]
when I run your code locally against the test file I get:

~~~
[bobbelderbos@imac 03 (solutions)]$ nosetests
FFF
======================================================================
FAIL: test_get_similarities (test_tags.test_tags)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bobbelderbos/code/challenges/03/test_tags.py", line 41, in test_get_similarities
    self.assertEqual(len(similar_tags), 3)
AssertionError: 4 != 3

======================================================================
FAIL: test_get_tags (test_tags.test_tags)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bobbelderbos/code/challenges/03/test_tags.py", line 28, in test_get_tags
    self.assertEqual(len(set(self.tags)), 100)
AssertionError: 102 != 100

======================================================================
FAIL: test_get_top_tags (test_tags.test_tags)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bobbelderbos/code/challenges/03/test_tags.py", line 37, in test_get_top_tags
    self.assertIn(tag, pybites_tags.items())
AssertionError: ('github', 4) not found in dict_items([('2vs3', 1), ('3.6', 3), ('algorithms', 1), ('APIs', 1), ('assert', 1), ('asyncio', 1), ('automation', 1), ('beautifulsoup', 1), ('beginners', 4), ('best practices', 5), ('blog', 1), ('bookcision', 1), ('books', 3), ('bs4', 1), ('challenge', 1), ('challenges', 2), ('cleancode', 5), ('code', 3), ('code challenges', 3), ('code review', 2), ('coding style', 1), ('collections', 4), ('conda', 1), ('contextmanagers', 1), ('cron', 1), ('data', 1), ('data science', 2), ('data structures', 2), ('decorators', 1), ('deque', 1), ('dicts', 1), ('distribute', 1), ('ebook', 1), ('features', 1), ('feedparser', 2), ('flask', 1), ('fork', 1), ('formatting', 1), ('game', 1), ('games', 1), ('generator', 1), ('generators', 3), ('git', 2), ('git flow', 1), ('github', 5), ('gotchas', 1), ('guidelines', 1), ('HN', 1), ('html', 1), ('iterators', 2), ('itertools', 2), ('json', 1), ('kindle', 1), ('learning', 7), ('logging', 2), ('matplotlib', 1), ('max', 1), ('namedtuple', 2), ('news', 3), ('notebooks', 1), ('packaging', 1), ('pandas', 1), ('pelican', 3), ('pep8', 2), ('performance', 2), ('permutations', 1), ('pip', 3), ('podcasts', 3), ('publishing', 2), ('pybites', 3), ('pytest', 1), ('python', 10), ('pythonic', 4), ('pythontips', 1), ('pyvenv', 1), ('random', 1), ('readability', 1), ('refactoring', 3), ('release', 1), ('resources', 1), ('review', 1), ('rss', 2), ('scrabble', 3), ('secrets', 1), ('sets', 1), ('stdlib', 1), ('tdd', 1), ('Template strings', 1), ('tips', 6), ('tools', 1), ('tricks', 5), ('tweepy', 1), ('twitter', 2), ('twitterapi', 1), ('typing', 1), ('venv', 2), ('vim', 2), ('virtualenv', 4), ('webscraping', 1), ('zip', 1)])

----------------------------------------------------------------------
Ran 3 tests in 0.081s

FAILED (failures=3)
~~~

**Comment by bbelderbos** [comment]
please only add files for one code challenge (PCC)

**Comment by pybites** [comment]
Hope you can sort it out with above instructions. If not seek help on Slack. Closing PR, open a new one when you have passing tests.

**Pull request closed without merging**
