### PR TITLE
Wonderfulboyx submission

### PR DESCRIPTION
**Pull request by wonderfulboyx**
Wonderfulboyx PR

### CODE REVIEW

**Comment by pybites** [comment]
Seems there are some merge conflicts in 21:

+<<<<<<< HEAD
 +=======
  
 +>>>>>>> upstream/community
 +=======


As it is all your code, I will merge this in to get / try 22 code. Feel free to solve the conflicts and submit again.

**Comment by pybites** [comment]
would be nice to include setting-example.ini (and ignore setting.ini in .gitignore), also missing the requirements.txt file? thanks

**Comment by pybites** [comment]
What is the additional value of Selenium/ PhantomJS here? Seems you only use it to pull down the content: 

soup = BeautifulSoup(self.selenium_resource(), "lxml")

If so, maybe there is an easier way?

**Comment by pybites** [comment]
I like you made it modular and you used a config file! Good job

Btw should this be once a day?
schedule.every().hour.do(packt_scraper.update_info)

**Comment by pybites** [comment]
Maybe you can read this from config as well?

msg['From'] = self.FROM_ADDR

Tends to be static, no?


I would abstract this out into a constant (top) or get it via command line arg: 

addr = "your_email"  (not add your email to script / version control)


By the way, minor detail: there is a nicer way to format make_message():

>>> info = dict(title='the book', description='this book is about')
>>> '''title = {title}
...    description = {description}'''.format(**info)
'title = the book\n   description = this book is about'


Thanks for joining, you seem to be learning a lot (we do too!)

**Comment by wonderfulboyx** [comment]
Thank you for comment. I'll keep learning.

I added feature that get sender and sending address from command line.
and I modified code of formatting message strings.

I used selenium because I could not get time left using BeautifulSoup and urllib that like `soup = BeautifulSoup(urllib.request.Request(url))`

**Pull request merged**
