### PR TITLE
Challenge 13 - top directors 

### PR DESCRIPTION
**Pull request by atakume**
Suggestions welcome.

### CODE REVIEW

**Comment by pybites** [comment]
Cool, thanks, the merge worked. 

I need to check out groupby, seems adequate here. It seems the way to go as well if you go SQL/Pandas with this one. 

Maybe you could use enumerate for the print / counter bit?

**Comment by atakume** [comment]
Thanks for comment and merge. 
I'll check out enumerate function and SQL package.

**Comment by bbelderbos** [comment]
SQL I meant as a concept, not package, sorry. I saw somebody loading the data into sqlite and solving this with one SQL statement, very cool! 

I can't wait to redo this one in Pandas after studying it some more, I will let you know ...

**Comment by atakume** [comment]
Oh this way, ok, thanks for explanation. 
With pandas it should be extra easy. Have fun with it.

**Pull request merged**
