### PR TITLE
PCC28

### PR DESCRIPTION
**Pull request by shibasisp**
ATTENTION: before clicking "Create Pull Request" please submit some meta data, thanks!

Difficulty level (1-10): [5]
Estimated time spent (hours): [Around 5 hours]
Completed (yes/no): [yes, runs locally but doesn't show graph on heroku]
I stretched my coding skills (yes/no): [yes]
I want to be notified about new challenges (if yes enter email): [shibasishpatel@live.in]
Other feedback (what can we improve?): [You are already doing great!]

### CODE REVIEW

**Comment by pybites** [comment]
awesome, we will merge and check it out ...

**Comment by mjhea0** [comment]
@shibasisp you are trying to load insecure (`http`) dependencies over `https` on Heroku. Remove the protocol from your dependencies and they will load fine. 

For example...

Change:

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
```

To:

```html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
```

**Comment by shibasisp** [comment]
Thanks @mjhea0 ! It worked. :+1:

**Comment by bbelderbos** [comment]
Thanks Mike, nice to see you guys collaborating on this challenge.

**Pull request merged**
