### PR TITLE
Community

### PR DESCRIPTION
**Pull request by RedHoodJT1988**
ATTENTION: before clicking "Create Pull Request" please submit some meta data, thanks!

Difficulty level (1-10): [1]
Estimated time spent (hours): [5]
Completed (yes/no): [yes]
I stretched my coding skills (if yes what did you learn?): [I was able to stretch my coding skills by building a complete game GUI and playable game with Pygame. ]
Other feedback (what can we improve?): []

### CODE REVIEW

**Comment by RedHoodJT1988** [comment]
I'm not sure why there is so many files. Not sure what I did wrong.

**Comment by schattencheg** [comment]
You need to follow instructions step-by-step one more time from beginning.

**Comment by RedHoodJT1988** [comment]
Ok sounds good.

**Comment by RedHoodJT1988** [comment]
Ok sorry about that. I was able to revert my commits and reset them.
Everything should be fine now. Should just be my one file.

**Pull request closed without merging**
