### PR TITLE
PCC01 Abdulkadir98

### PR DESCRIPTION
**Pull request by Abdulkadir98**
ATTENTION: before clicking "Create Pull Request" please submit some meta data, thanks!

Difficulty level (1-10): [2]
Estimated time spent (hours): [1]
Completed (yes/no): [yes]
I stretched my coding skills (if yes what did you learn?): [file manipulation]
Other feedback (what can we improve?): []

### CODE REVIEW

**Comment by jcastle13** [comment]
Hello @Abdulkadir98,

Wanted to know why are you manipulating wordvalue.py file twice?  You should only need to manipulate it within your own branch.  The wordvalue.py file in '01' will be changed which isn't something we would want.

**Comment by Abdulkadir98** [comment]
I was not aware of that, I'll create a new branch.

**Comment by jcastle13** [comment]
Don’t think you need to create a new branch since you have one already.  Just need to remove the file from 01/wordvalue.py

**Comment by jcastle13** [comment]
Why did you close it?

**Pull request closed without merging**
