### PR TITLE
PCC25 santiagobenitez

### PR DESCRIPTION
**Pull request by santiagobenitez**
ATTENTION: before clicking "Create Pull Request" please submit some meta data, thanks!

This is my first ever python code so I can imagine it won't be as pythonic as you'd expect it to be and also it might look very rusty. I did it mainly for 2 reasons:

1. Because I come from .NET, Python looked to be a great choice since it's on the other side of the road both from a theory point of view and from a philosophical point of view.
2. I believe that coding is the best way of learning and think that what you do is a great idea to get started with a language. So thank you in advance for your time and feedback. 

I did the first two parts of the task:

1. I am using the api of hemoviedb.org
2. The script provides filters for: genre, year and vote average/rating

As notification system I decided to use emails to keep it as simple as possible. Because I didn't add subscription logic, I've hardcoded the recipient (abcd12345@mailinator.com). It's a public mail so you'd be able to double check that the email was sent. This can definitely be improved so If you think it's not enough just let me know. For sending the emails I am using mailgun and for running the script you'll need two environment variables MAILGUN_KEY and MAILGUN_DOMAIN.

Find below examples of how to use the script:

- python movies.py --genre 27,14 --voteaverage 4 --year 2017
- python movies.py

Also if you run:
- python movies.py --help

you'll see a description of each of the filters

Difficulty level (1-10): [4]
Estimated time spent (hours): [3]
Completed (yes/no): [yes]
I stretched my coding skills (yes/no): [yes]
Other feedback: []

### CODE REVIEW

**Comment by pybites** [comment]
Great, I will merge and take a look. Thanks

**Comment by bbelderbos** [comment]
Wow great job if that's your first Python script! Featuring it in our review. I will point out some small things in more detail later this week.

**Comment by santiagobenitez** [comment]
Thanks! no problem, I'll have a look at them. Also I'll really appreciate if you have time to recommend me stuff to read about Python or any project you'd like me to contribute in order to keep learning. The book I've started to read is Python Essential Reference.

**Comment by bbelderbos** [comment]
Hey how was this your first Python script?! It looked pretty good!

**Comment by bbelderbos** [comment]
How is the essential reference? We did a resource post, you probably find something useful there: https://pybit.es/python-resources.html

**Comment by bbelderbos** [comment]
Project / contribute. That would be cool. What would you like to build? We are about to kick off a new 100 days project to learn Django.

**Comment by santiagobenitez** [comment]
hey thanks! Yes it was my first script but I have more than 6 years experience doing software development so that's why maybe it was not that bad, but honestly didn't know whether to push it or not cause I felt a bit embarrassed about it, it felt like starting again, which is very fun but well... 

Also looked at your implementation I liked how you used shelves and pickle, didn't know they existed of course.

What is it going to be the Django project about? it sounds interesting. Django would definitely be something I'd be interested in cause I know it is one of the most (if not the most) used frameworks in python.

**Comment by bbelderbos** [comment]
Thanks, it was nice for playing around, but I probably should have used a DB / SQLite to make it more extensible.

Django ... we're defining that now. Maybe you want to join our private Slack and brainstorm with us. If so send us your email to pybitesblog at gmail dot com. Cheers

**Comment by santiagobenitez** [comment]
great, i've sent you an email, let me know if you got it, thanks

**Comment by bbelderbos** [comment]
yep thanks, you're invited to our Slack

**Pull request merged**
