### PR TITLE
Pcc21 submission - wattapp!

### PR DESCRIPTION
**Pull request by dseptem**
Hope you guys like it :+1:

### CODE REVIEW

**Comment by dseptem** [comment]
No pretty CSS or Bootstrap this time though, I focused the functionality!

**Comment by pybites** [comment]
Nice work, as per new rule leaving this PR open for 1,5 week more if you have adjustments and to give us some time to review. Also don't want to peak too much before doing the challenge myself :)
Thanks 👍

**Comment by pybites** [comment]
OK leaving open won't work: I needed to merge in the changes to test locally and that auto-closes the PR. But after closure we can still comment on it.

**Comment by pybites** [comment]
Hey Dante, nice one, looks good!

Quick review:
- Maybe load SECRET_KEY from env with os.environ.get?

- I added **.db to .gitignore to ignore DB from version control

- I like that you used Flask plugins: flask_sqlalchemy, flask_wtf, wtforms

- Good PEP8 style and docstrings/documentation :)

- Maybe I would add the name of the device, if I see a high wattage I would wonder which device caused it.

- kW/h can be different per device? If not, maybe extract that out and make it a constant, or if configurable a session variable?

Again great work

**Comment by dseptem** [comment]
1) Not sure about the SECRET_KEY, what's the advantage?
2) Thanks, .gitignore confuses me sometimes.
3) They seemed to make the work much faster and were easy to understand.
4) I'd like to make proper tests for this, but Flask-testing eludes me yet.
5) Good point, I should add a device name field.
6) Yes, the kW/h can be different, just as the device name, so according to (5) and (6) I'll add that field.

**Pull request merged**
