### PR TITLE
PCC02 - My Solution.

### PR DESCRIPTION
**Pull request by cod3Ghoul**
ATTENTION: before clicking "Create Pull Request" please submit some meta data, thanks!

Difficulty level (1-10): [7]
Estimated time spent (hours): [10]
Completed (yes/no): [Yes]
I stretched my coding skills (if yes what did you learn?): [I learned a lot about how classes work in Python vs. C++. I learned about how to use several modules like collections.Counter, operator.contains, etc. I learned a lot more about trying to keep my code within PEP 8 standards and how to use the debugger in Pycharm to efficiently resolve the bugs in my code.]
Other feedback (what can we improve?): [The unittest written for this challenge will not pass because it fails to take into account the fact that I wrote a class for the part of the program that determines all the permutations for the draw (i.e. the unittest doesn't import the class, so it breaks). But, I did manually test the game and I'm sure it will pass any new unittests written for it.]

### CODE REVIEW

**Comment by pybites** [comment]
will check it, I challenge you to adjust the tests :)

can you ignore the dot files and take files of PCC01 out of this PR?

**Comment by cod3Ghoul** [comment]
And I take up your challenge sir!

**Comment by cod3Ghoul** [comment]
Ok, I was able to remove the PCC01 commits in this PR for PCC02 by using 'git rebase...'
Now, I'll work on re-writing the unit test

**Comment by pybites** [comment]
rebase, sounds scary. cool man, will run it locally now after merge and pull.

**Pull request merged**
