### PR TITLE
PCC04 niilz

### PR DESCRIPTION
**Pull request by niilz**
Difficulty level (1-10): [6]
Estimated time spent (hours): [3]
Completed (yes/no): [Yes]
I stretched my coding skills (if yes what did you learn?): [- more git commands (commited to the wrong branch and had to use git cherry-pick)
- reading and really using docs (twitter and tweepy)
- using named tuples
- csv module
- using a datetime object
- examining tests to refine your own interface/code]
Other feedback (what can we improve?): [I really love your site and the challenges. I had some trouble working out what the test wanted from me. But that also helped how to really implement my interface (TDD light so to speak ;)
And this was now the first real experience of "docs can be hard". The tweepy docs are ok, but the most basic thing: "how to get a tweet" is just not easy to find. But I guess that is where the community (me included) should spend some time improving those documentations.
Thanks for the challenge. Nothing negative to say about it.]

### CODE REVIEW

**Comment by pybites** [comment]
Great feedback and documenting of your learning, thanks @niilz 
Yeah `tweepy` requires some trial and error but it does make it pretty straight forward. Twitter API is less accessible these days no? Not so easy to get an app approved, no?

**Comment by pybites** [comment]
Hey you committed my tweets, did you ask permission? Just kidding lol
Keep calm and code in Python, if you have more challenge ideas just open an issue or ping us on Slack
Cheers
Bob

**Comment by niilz** [comment]
Oh Jeeez, so sorry. I think I wasn‘t reall aware. That was not intended. I should have thought about it.

I will watch out for similar things in the future.

Best Regards
niilz

Am 21.02.2019 um 11:53 schrieb PyBites <notifications@github.com<mailto:notifications@github.com>>:


Hey you committed my tweets, did you ask permission? Just kidding lol
Keep calm and code in Python, if you have more challenge ideas just open an issue or ping us on Slack
Cheers
Bob

**Comment by bbelderbos** [comment]
I meant it as a joke :) - sorry

**Comment by niilz** [comment]
Oh ok. 😅 I would have totally understood the complaint though.
Lucky me

Am 21.02.2019 um 18:53 schrieb Bob Belderbos <notifications@github.com<mailto:notifications@github.com>>:


I meant it as a joke :) - sorry

**Pull request merged**
