### PR TITLE
PCC01 d3prof3t

### PR DESCRIPTION
**Pull request by d3prof3t**
- calculate the word that has the most value in scrabble

- because the challenge says to do so

- by making the code pass the tests

ATTENTION: before clicking "Create Pull Request" please submit some meta data, thanks!

Difficulty level (1-10): [1]
Estimated time spent (hours): [1]
Completed (yes/no): [Yes]
I stretched my coding skills (if yes what did you learn?): [just realised how much python dictionaries can make the code efficient in terms of lookup]
Other feedback (what can we improve?): []

### CODE REVIEW

**Comment by d3prof3t** [comment]
@pybites seems like the test case where we check the len of the list of words is checking for more one more than the actual. Is it just me? Can you please confirm.

**Comment by pybites** [comment]
nope, not for m:

        self.assertEqual(len(words), 235886)

$ wc -l dictionary.txt
  235886 dictionary.txt

To merge changes please put the files in 01/d3prof3t/

**Comment by d3prof3t** [comment]
@pybites Refactored the project structure and got the original test to pass :) . Let me know if the PR looks good and is good for merge?

**Comment by d3prof3t** [comment]
Closing this because checkout was from wrong branch. Please refer the correct PR [here](https://github.com/pybites/challenges/pull/228)

**Pull request closed without merging**
