### PR TITLE
PCC40 dseptem

### PR DESCRIPTION
**Pull request by dseptem**
Difficulty level (1-10): [5]
Estimated time spent (hours): [4]
Completed (yes/no): [Kinda]
I stretched my coding skills (if yes what did you learn?): [Apscheduler, Flask, AngularJS]
Please include a short blurb about your submission for our review post: [Easier than expected, but got kinda lazy on the AngularJS part =P. IMPORTANT: You need to have Elasticsearch running on localhost:9200 for this to work!]

### CODE REVIEW

**Comment by dseptem** [comment]
long time since a pull request, hope I didnt miss anything

**Comment by dseptem** [comment]
added requirements and a very lazy readme, sorry =P

**Comment by bbelderbos** [comment]
cool! I am gonna try this locally
thanks

**Comment by pybites** [comment]
merging into community to pull the code and try
good job

**Comment by bbelderbos** [comment]
A readme would be nice, but it was not hard to get it working on my mac: `brew install elasticsearch`  run `elasticsearch` (no options) and run the `scraper.py` to import the tweets, `python app.py`. UI looks great. Search seems only whole word match only? 
Great job!

**Comment by dseptem** [comment]
Yeah, I didn't get the search-as-you-type thing done.
Probably need to tweak elasticsearch and/or the AngularJS.

**Pull request merged**
