### PR TITLE
Pcc52

### PR DESCRIPTION
**Pull request by russb1119**
ATTENTION: before clicking "Create Pull Request" please submit some meta data, thanks!

Difficulty level (1-10): [5]
Estimated time spent (hours): [1.5]
Completed (yes/no): [yes]
I stretched my coding skills (if yes what did you learn?): [yes, I wanted to user to be able to be able to just let the program run as long as they wanted. Probably not the most graceful way to handle it, but I ended up catching a KeyboardInterrupt and excepting the final outputs.]
Other feedback (what can we improve?): [Fun project!]

### CODE REVIEW

**Comment by russb1119** [comment]
Updated syntax for input() vs raw_input()

**Comment by russb1119** [comment]
I am not sure if I am doing this pull request thing right!! :(

**Comment by pybites** [comment]
All good, just need to use the _challenges_ branch as Base, did you have any issues with the instructions on the platform?

**Comment by pybites** [comment]
Nice work/learning btw

**Pull request merged**
